AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Cpu:
    AllowedValues:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    Default: 512
    Type: String

  Host:
    Type: String

  ListenerPriority:
    Default: 1
    Type: String

  LoadBalancerListenerArn:
    Type: String

  Memory:
    AllowedValues:
      - 512
      - 1024
      - 2048
      - 4096
      - 8192
      - 16384
      - 30720
    Default: 1024
    Type: String

  Name:
    Default: jenkins
    Type: String

  PrivateSubnetList:
    Type: CommaDelimitedList

  Sequence:
    Default: 1
    Type: String

  Stage:
    Type: String

  VpcCidr:
    Type: String

  VpcId:
    Type: String

#Mappings:

#Conditions:

Resources:

  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['-', [ECSLogGroup, !Ref 'AWS::StackName']]
      RetentionInDays: 14

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: jenkins-cluster

  EcsService:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerListener
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref JenkinsTaskDefinition
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 300
      LaunchType: FARGATE
      PlatformVersion: 1.4.0
      DeploymentConfiguration:
        MinimumHealthyPercent: 0
        MaximumPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !GetAtt VPCStack.Outputs.PrivateSubnet1
            - !GetAtt VPCStack.Outputs.PrivateSubnet2
          SecurityGroups:
            - !GetAtt JenkinsSecurityGroup.GroupId
      LoadBalancers:
        - ContainerName: jenkins
          ContainerPort: 8080
          TargetGroupArn: !Ref JenkinsTargetGroup

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: jenkins
          Image: jenkins/jenkins:lts
          PortMappings:
            - ContainerPort: 8080
          MountPoints:
            - SourceVolume: jenkins-home
              ContainerPath: /var/jenkins_home
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudwatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: jenkins
      Cpu: !Ref Cpu
      ExecutionRoleArn: !Ref JenkinsExecutionRole
      Family: !Sub jenkins-task
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
        - EC2
      TaskRoleArn: !Ref JenkinsRole
      Volumes:
        - Name: jenkins-home
          EFSVolumeConfiguration:
            AuthorizationConfig:
              AccessPointId: !Ref EfsAccessPointResource
              IAM: ENABLED
            FilesystemId: !Ref EfsFileSystem
            TransitEncryption: ENABLED

  EfsAccessPointResource:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EfsFileSystem
      PosixUser:
        Uid: '1000'
        Gid: '1000'
      RootDirectory:
        CreationInfo:
          OwnerGid: '1000'
          OwnerUid: '1000'
          Permissions: '755'
        Path: '/jenkins-home'

  EfsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: jenkins-home

  EfsMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EfsFileSystem
      SubnetId: !Select [ 0, !Ref PrivateSubnetList ]
      SecurityGroups:
        - !GetAtt EfsSecurityGroup.GroupId

  EfsMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EfsFileSystem
      SubnetId: !Select [ 1, !Ref PrivateSubnetList ]
      SecurityGroups:
        - !GetAtt EfsSecurityGroup.GroupId

  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Jenkins Efs
      SecurityGroupIngress:
        - CidrIp: !Ref VpcCidr
          IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049

  LoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref Host
      ListenerArn: !Ref LoadBalancerListenerArn
      Priority: !Ref ListenerPriority

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /login
      Name: !Sub ${Name}-${Stage}-${Sequence}-target-group
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 10

#Outputs:
